services:
  - type: web
    name: importease
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://YOUR_NEON_HOST/YOUR_NEON_DB?sslmode=require
      - key: DB_USERNAME
        value: YOUR_NEON_USERNAME
      - key: DB_PASSWORD
        value: YOUR_NEON_PASSWORD
      - key: BREVO_API_KEY
        value: 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
      - key: PORT
        value: 8080
      - key: PAYSTACK_SECRET_KEY
        sync: false