services:
  - type: web
    name: importease
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://ep-orange-credit-ai8r6tum.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_hn32EHNbTvwG
      - key: BREVO_API_KEY
        value: HER_REAL_BREVO_KEY_HERE
      - key: PORT
        value: 8080