services:
  - type: web
    name: importease
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: BREVO_API_KEY
        value: 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
      - key: PORT
        value: 8080
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: CLOUDINARY_URL
        value: cloudinary://625873576545436:e40-6UmsnPyCyj_9mVrM4skEmbc@z9a7vegw