spring.application.name=ImportEase

# ==========================================================
# LOCAL TEST CONFIGURATION (HARDCODED FOR NEON)
# ==========================================================
spring.datasource.url=jdbc:postgresql://ep-orange-credit-ai8r6tum.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_hn32EHNbTvwG

# Auto-updates your Neon cloud tables on application startup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect