spring.datasource.url=jdbc:postgresql://localhost:5432/ImportEase
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
server.port=5000