spring.application.name=ImportEase

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/importease?sslmode=disable}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

sendgrid.api.key=${SENDGRID_API_KEY:}
sendgrid.from.name=${SENDGRID_FROM_NAME:}
sendgrid.from.email=${SENDGRID_FROM_EMAIL:}

twilio.account.sid=${TWILIO_ACCOUNT_SID:}
twilio.auth.token=${TWILIO_AUTH_TOKEN:}
twilio.from.number=${TWILIO_FROM_NUMBER:}

cloudinary.url=${CLOUDINARY_URL:}

paystack.secret.key=${PAYSTACK_SECRET_KEY:}
paystack.base.url=https://api.paystack.co
app.base.url=${APP_BASE_URL:https://importease-backend.onrender.com}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB